### create a book
POST http://localhost:3000/bookings/create/beff2247-cd05-414d-831a-14059ad186c6
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YTE3OWZhNy05YTY2LTQyNmMtYjBmMi0zNTBiNjM2NjI4ZDIiLCJ1c2VyTmFtZSI6IktyaXN0ZW4iLCJwaG9uZU51bWJlciI6IjAxNDMyNzY1OTQiLCJlbWFpbCI6ImtyaXN0ZW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkaDd3V2U0azBSaWxQSVI2a1duUlp3dTNlV3lTWkp5akl1Y1kwcklqbmFoN3BsNHNFbzdweTIiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMzAzMzQ5LCJleHAiOjE3MjEzMTA1NDl9.ApIyMiqkSY9LpQLIikATGXCkTJeYa7yvPvFNVJ52mBo

{
    "ticketType" : "groups"
}

### update a book
PUT http://localhost:3000/bookings/update/beff2247-cd05-414d-831a-14059ad186c6
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YTE3OWZhNy05YTY2LTQyNmMtYjBmMi0zNTBiNjM2NjI4ZDIiLCJ1c2VyTmFtZSI6IktyaXN0ZW4iLCJwaG9uZU51bWJlciI6IjAxNDMyNzY1OTQiLCJlbWFpbCI6ImtyaXN0ZW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkaDd3V2U0azBSaWxQSVI2a1duUlp3dTNlV3lTWkp5akl1Y1kwcklqbmFoN3BsNHNFbzdweTIiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMzAzMzQ5LCJleHAiOjE3MjEzMTA1NDl9.ApIyMiqkSY9LpQLIikATGXCkTJeYa7yvPvFNVJ52mBo

{
    "ticketType" : "couple"
}

### Get all bookings
GET http://localhost:3000/bookings/allBookings/
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YTE3OWZhNy05YTY2LTQyNmMtYjBmMi0zNTBiNjM2NjI4ZDIiLCJ1c2VyTmFtZSI6IktyaXN0ZW4iLCJwaG9uZU51bWJlciI6IjAxNDMyNzY1OTQiLCJlbWFpbCI6ImtyaXN0ZW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkaDd3V2U0azBSaWxQSVI2a1duUlp3dTNlV3lTWkp5akl1Y1kwcklqbmFoN3BsNHNFbzdweTIiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMzAzMzQ5LCJleHAiOjE3MjEzMTA1NDl9.ApIyMiqkSY9LpQLIikATGXCkTJeYa7yvPvFNVJ52mBo

### cancel a book
DELETE http://localhost:3000/bookings/delete/1e652781-7e91-4d49-92db-00ef739fbbdd
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YTE3OWZhNy05YTY2LTQyNmMtYjBmMi0zNTBiNjM2NjI4ZDIiLCJ1c2VyTmFtZSI6IktyaXN0ZW4iLCJwaG9uZU51bWJlciI6IjAxNDMyNzY1OTQiLCJlbWFpbCI6ImtyaXN0ZW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkaDd3V2U0azBSaWxQSVI2a1duUlp3dTNlV3lTWkp5akl1Y1kwcklqbmFoN3BsNHNFbzdweTIiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMzAzMzQ5LCJleHAiOjE3MjEzMTA1NDl9.ApIyMiqkSY9LpQLIikATGXCkTJeYa7yvPvFNVJ52mBo

### Get booked users
GET http://localhost:3000/bookings/bookedUsers/
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YTE3OWZhNy05YTY2LTQyNmMtYjBmMi0zNTBiNjM2NjI4ZDIiLCJ1c2VyTmFtZSI6IktyaXN0ZW4iLCJwaG9uZU51bWJlciI6IjAxNDMyNzY1OTQiLCJlbWFpbCI6ImtyaXN0ZW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkaDd3V2U0azBSaWxQSVI2a1duUlp3dTNlV3lTWkp5akl1Y1kwcklqbmFoN3BsNHNFbzdweTIiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMzAzMzQ5LCJleHAiOjE3MjEzMTA1NDl9.ApIyMiqkSY9LpQLIikATGXCkTJeYa7yvPvFNVJ52mBo

### Get confirmed bookings
GET http://localhost:3000/bookings/confirmedBookings
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YTE3OWZhNy05YTY2LTQyNmMtYjBmMi0zNTBiNjM2NjI4ZDIiLCJ1c2VyTmFtZSI6IktyaXN0ZW4iLCJwaG9uZU51bWJlciI6IjAxNDMyNzY1OTQiLCJlbWFpbCI6ImtyaXN0ZW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkaDd3V2U0azBSaWxQSVI2a1duUlp3dTNlV3lTWkp5akl1Y1kwcklqbmFoN3BsNHNFbzdweTIiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMzExMTI1LCJleHAiOjE3MjEzMTgzMjV9.RAwlWIuAKWt886epcYZNGO7TqR7I4w6WNNIdN_NDXmQ

### update book status
PUT http://localhost:3000/bookings/updateStatus/cdca7e99-f194-4428-9e0c-f284b058ff4f
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YTE3OWZhNy05YTY2LTQyNmMtYjBmMi0zNTBiNjM2NjI4ZDIiLCJ1c2VyTmFtZSI6IktyaXN0ZW4iLCJwaG9uZU51bWJlciI6IjAxNDMyNzY1OTQiLCJlbWFpbCI6ImtyaXN0ZW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkaDd3V2U0azBSaWxQSVI2a1duUlp3dTNlV3lTWkp5akl1Y1kwcklqbmFoN3BsNHNFbzdweTIiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMzAzMzQ5LCJleHAiOjE3MjEzMTA1NDl9.ApIyMiqkSY9LpQLIikATGXCkTJeYa7yvPvFNVJ52mBo