### create a book
POST http://localhost:3000/bookings/create/beff2247-cd05-414d-831a-14059ad186c6
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ZjRhMTA3Mi1jOTM3LTQ3ZDktYmNjZi1lZTViODBhNDE5OGQiLCJ1c2VyTmFtZSI6IkRhbjI1IiwicGhvbmVOdW1iZXIiOiIwMTU0MTY2NTQzIiwiZW1haWwiOiJkYW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkcWhYeHUuS0Y1YUhuTEVCMHhKLlpTZVhodzd2NmdRQ3hYbmZORnBGM2dMd3hpUncwcWdPU0siLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJzb3V0aEFmcmljYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZSI6ZmFsc2UsImlhdCI6MTcyMTM5NzQ2MSwiZXhwIjoxNzIxNDA0NjYxfQ.wEhCHuJbWBpt_QLc-Ieec3jG5R8RcPYMoY765KDIerc

{
    "ticketType" : "couple"
}

### update a book
PUT http://localhost:3000/bookings/update/b2d2f5c2-9874-4ff3-92ab-5f0f45405fb8
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYWRjOWQ4ZS02OTlkLTQxY2YtYmJiOC1mYjgxYTA3YmUyNjMiLCJ1c2VyTmFtZSI6Ik5hb21pQyIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU0MyIsImVtYWlsIjoibmFvbWljaGVnZTI1MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkZ1NCclprLmQyNExFTnN0UkFpQ05sdXVVUUx4MUNaUERFaVRiNVJMbE5pbmx1dC9qYlk3aW0iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJLaWVuaSIsInVzZXJSb2xlIjoiYWRtaW4iLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjEzNzU0MTcsImV4cCI6MTcyMTM4MjYxN30.CGw2jr7NXomhGD9QDYd5x_f52X5726pM4AJSZkUOk6w

{
    "ticketType" : "single"
}

### Get all bookings
GET http://localhost:3000/bookings/allBookings/
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ZjRhMTA3Mi1jOTM3LTQ3ZDktYmNjZi1lZTViODBhNDE5OGQiLCJ1c2VyTmFtZSI6IkRhbjI1IiwicGhvbmVOdW1iZXIiOiIwMTU0MTY2NTQzIiwiZW1haWwiOiJkYW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkcWhYeHUuS0Y1YUhuTEVCMHhKLlpTZVhodzd2NmdRQ3hYbmZORnBGM2dMd3hpUncwcWdPU0siLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJzb3V0aEFmcmljYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZSI6ZmFsc2UsImlhdCI6MTcyMTM5NzQ2MSwiZXhwIjoxNzIxNDA0NjYxfQ.wEhCHuJbWBpt_QLc-Ieec3jG5R8RcPYMoY765KDIerc

### cancel a book
DELETE http://localhost:3000/bookings/delete/b2d2f5c2-9874-4ff3-92ab-5f0f45405fb8
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYWRjOWQ4ZS02OTlkLTQxY2YtYmJiOC1mYjgxYTA3YmUyNjMiLCJ1c2VyTmFtZSI6Ik5hb21pQyIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU0MyIsImVtYWlsIjoibmFvbWljaGVnZTI1MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkZ1NCclprLmQyNExFTnN0UkFpQ05sdXVVUUx4MUNaUERFaVRiNVJMbE5pbmx1dC9qYlk3aW0iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJLaWVuaSIsInVzZXJSb2xlIjoiYWRtaW4iLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjEzNzU0MTcsImV4cCI6MTcyMTM4MjYxN30.CGw2jr7NXomhGD9QDYd5x_f52X5726pM4AJSZkUOk6w

### Get booked users
GET http://localhost:3000/bookings/bookedUsers/
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYWRjOWQ4ZS02OTlkLTQxY2YtYmJiOC1mYjgxYTA3YmUyNjMiLCJ1c2VyTmFtZSI6Ik5hb21pQyIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU0MyIsImVtYWlsIjoibmFvbWljaGVnZTI1MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkZ1NCclprLmQyNExFTnN0UkFpQ05sdXVVUUx4MUNaUERFaVRiNVJMbE5pbmx1dC9qYlk3aW0iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJLaWVuaSIsInVzZXJSb2xlIjoiYWRtaW4iLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjEzNzU0MTcsImV4cCI6MTcyMTM4MjYxN30.CGw2jr7NXomhGD9QDYd5x_f52X5726pM4AJSZkUOk6w

### Get confirmed bookings
GET http://localhost:3000/bookings/confirmedBookings
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYWRjOWQ4ZS02OTlkLTQxY2YtYmJiOC1mYjgxYTA3YmUyNjMiLCJ1c2VyTmFtZSI6Ik5hb21pQyIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU0MyIsImVtYWlsIjoibmFvbWljaGVnZTI1MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkZ1NCclprLmQyNExFTnN0UkFpQ05sdXVVUUx4MUNaUERFaVRiNVJMbE5pbmx1dC9qYlk3aW0iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJLaWVuaSIsInVzZXJSb2xlIjoiYWRtaW4iLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjEzNzU0MTcsImV4cCI6MTcyMTM4MjYxN30.CGw2jr7NXomhGD9QDYd5x_f52X5726pM4AJSZkUOk6w

### update book status
PUT http://localhost:3000/bookings/updateStatus/cdca7e99-f194-4428-9e0c-f284b058ff4f
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYWRjOWQ4ZS02OTlkLTQxY2YtYmJiOC1mYjgxYTA3YmUyNjMiLCJ1c2VyTmFtZSI6Ik5hb21pQyIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU0MyIsImVtYWlsIjoibmFvbWljaGVnZTI1MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkZ1NCclprLmQyNExFTnN0UkFpQ05sdXVVUUx4MUNaUERFaVRiNVJMbE5pbmx1dC9qYlk3aW0iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJLaWVuaSIsInVzZXJSb2xlIjoiYWRtaW4iLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjEzNzU0MTcsImV4cCI6MTcyMTM4MjYxN30.CGw2jr7NXomhGD9QDYd5x_f52X5726pM4AJSZkUOk6w