### create a book
POST http://localhost:3000/bookings/create/932651fe-f99b-4cc3-9f2d-4639925015c0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MzI2NTFmZS1mOTliLTRjYzMtOWYyZC00NjM5OTI1MDE1YzAiLCJ1c2VyTmFtZSI6Ik5hb21pMjUiLCJwaG9uZU51bWJlciI6IjAxNTQxNjY1ODMiLCJlbWFpbCI6Im5hb21pQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEzJHdQOEQ1eENjLkpqanNSbjFlTjF6WnVzTTBtRlVCSHNwWkVBZE9KZURJQ3VWWng3T283WmRxIiwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aC9pZC9SLjUwNjMxYzMxN2U2NmVlYmY0OTAwYzRmNDljNjMyY2Q3P3Jpaz1hQ3RiTEg4WVlEeVlqdyZwaWQ9SW1nUmF3JnI9MCIsImxvY2F0aW9uIjoic291dGhBZnJpY2EiLCJ1c2VyUm9sZSI6Im1hbmFnZXIiLCJpc01hbmFnZXIiOnRydWUsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZSI6ZmFsc2UsImlhdCI6MTcyMTgwODQ5MSwiZXhwIjoxNzIxODE1NjkxfQ.seSdVFgqRtpv5sBbq3SqoUb3SMC9q2EtaEFyzHmXFW4

{
    "ticketType" : "couple"
}

### update a book
PUT http://localhost:3000/bookings/update/b2d2f5c2-9874-4ff3-92ab-5f0f45405fb8
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYWRjOWQ4ZS02OTlkLTQxY2YtYmJiOC1mYjgxYTA3YmUyNjMiLCJ1c2VyTmFtZSI6Ik5hb21pQyIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU0MyIsImVtYWlsIjoibmFvbWljaGVnZTI1MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkZ1NCclprLmQyNExFTnN0UkFpQ05sdXVVUUx4MUNaUERFaVRiNVJMbE5pbmx1dC9qYlk3aW0iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJLaWVuaSIsInVzZXJSb2xlIjoiYWRtaW4iLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjEzNzU0MTcsImV4cCI6MTcyMTM4MjYxN30.CGw2jr7NXomhGD9QDYd5x_f52X5726pM4AJSZkUOk6w

{
    "ticketType" : "single"
}

### Get all bookings
GET http://localhost:3000/bookings/allBookings/
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYWRjOWQ4ZS02OTlkLTQxY2YtYmJiOC1mYjgxYTA3YmUyNjMiLCJ1c2VyTmFtZSI6Ik5hb21pQyIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU0MyIsImVtYWlsIjoibmFvbWljaGVnZTI1MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkZ1NCclprLmQyNExFTnN0UkFpQ05sdXVVUUx4MUNaUERFaVRiNVJMbE5pbmx1dC9qYlk3aW0iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJLaWVuaSIsInVzZXJSb2xlIjoiYWRtaW4iLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjE4MDU4MTEsImV4cCI6MTcyMTgxMzAxMX0.i8NuzzG2iwN4etcCm0z-e1D6zH-KNzAHfqMGfG9Gzr0
### cancel a book
DELETE http://localhost:3000/bookings/delete/b2d2f5c2-9874-4ff3-92ab-5f0f45405fb8
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYWRjOWQ4ZS02OTlkLTQxY2YtYmJiOC1mYjgxYTA3YmUyNjMiLCJ1c2VyTmFtZSI6Ik5hb21pQyIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU0MyIsImVtYWlsIjoibmFvbWljaGVnZTI1MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkZ1NCclprLmQyNExFTnN0UkFpQ05sdXVVUUx4MUNaUERFaVRiNVJMbE5pbmx1dC9qYlk3aW0iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJLaWVuaSIsInVzZXJSb2xlIjoiYWRtaW4iLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjEzNzU0MTcsImV4cCI6MTcyMTM4MjYxN30.CGw2jr7NXomhGD9QDYd5x_f52X5726pM4AJSZkUOk6w

### Get booked users
GET http://localhost:3000/bookings/bookedUsers/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MzI2NTFmZS1mOTliLTRjYzMtOWYyZC00NjM5OTI1MDE1YzAiLCJ1c2VyTmFtZSI6Ik5hb21pMjUiLCJwaG9uZU51bWJlciI6IjAxNTQxNjY1ODMiLCJlbWFpbCI6Im5hb21pQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEzJHdQOEQ1eENjLkpqanNSbjFlTjF6WnVzTTBtRlVCSHNwWkVBZE9KZURJQ3VWWng3T283WmRxIiwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aC9pZC9SLjUwNjMxYzMxN2U2NmVlYmY0OTAwYzRmNDljNjMyY2Q3P3Jpaz1hQ3RiTEg4WVlEeVlqdyZwaWQ9SW1nUmF3JnI9MCIsImxvY2F0aW9uIjoic291dGhBZnJpY2EiLCJ1c2VyUm9sZSI6Im1hbmFnZXIiLCJpc01hbmFnZXIiOnRydWUsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZSI6ZmFsc2UsImlhdCI6MTcyMTgwODQ5MSwiZXhwIjoxNzIxODE1NjkxfQ.seSdVFgqRtpv5sBbq3SqoUb3SMC9q2EtaEFyzHmXFW4

### Get confirmed bookings
GET http://localhost:3000/bookings/confirmedBookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYWRjOWQ4ZS02OTlkLTQxY2YtYmJiOC1mYjgxYTA3YmUyNjMiLCJ1c2VyTmFtZSI6Ik5hb21pQyIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU0MyIsImVtYWlsIjoibmFvbWljaGVnZTI1MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkZ1NCclprLmQyNExFTnN0UkFpQ05sdXVVUUx4MUNaUERFaVRiNVJMbE5pbmx1dC9qYlk3aW0iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJLaWVuaSIsInVzZXJSb2xlIjoiYWRtaW4iLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjE4MDU4MTEsImV4cCI6MTcyMTgxMzAxMX0.i8NuzzG2iwN4etcCm0z-e1D6zH-KNzAHfqMGfG9Gzr0

### update book status
PUT http://localhost:3000/bookings/updateStatus/cdca7e99-f194-4428-9e0c-f284b058ff4f
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYWRjOWQ4ZS02OTlkLTQxY2YtYmJiOC1mYjgxYTA3YmUyNjMiLCJ1c2VyTmFtZSI6Ik5hb21pQyIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU0MyIsImVtYWlsIjoibmFvbWljaGVnZTI1MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkZ1NCclprLmQyNExFTnN0UkFpQ05sdXVVUUx4MUNaUERFaVRiNVJMbE5pbmx1dC9qYlk3aW0iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJLaWVuaSIsInVzZXJSb2xlIjoiYWRtaW4iLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjE4MDU4MTEsImV4cCI6MTcyMTgxMzAxMX0.i8NuzzG2iwN4etcCm0z-e1D6zH-KNzAHfqMGfG9Gzr0