### create an event
POST http://localhost:3000/events/create
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YTE3OWZhNy05YTY2LTQyNmMtYjBmMi0zNTBiNjM2NjI4ZDIiLCJ1c2VyTmFtZSI6IktyaXN0ZW4iLCJwaG9uZU51bWJlciI6IjAxNDMyNzY1OTQiLCJlbWFpbCI6ImtyaXN0ZW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkaDd3V2U0azBSaWxQSVI2a1duUlp3dTNlV3lTWkp5akl1Y1kwcklqbmFoN3BsNHNFbzdweTIiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMjk1MDAxLCJleHAiOjE3MjEzMDIyMDF9.UX1hixizrKo30T1oG77dLralb_UkFctzLPNv5sBwfSA

{
    "eventName" :"TaylorSwift concert",
    "startDate"  :"2024-7-22",
    "endDate" :"2024-7-26",
    "location" :"Instabul",
    "description" :"Rocking with Zayn Malik",
    "longDescription"  :"6 days concert,day and night..Snacks are provided..Book now!!" ,
    "images"  :"https://th.bing.com/th/id/OIP.KUvp0P4OpY0dvpDA26DclwHaHi?rs=1&pid=ImgDetMain",
    "single"  :"2000",
    "couple"  :"3500",
    "groups"  :"8000",
    "totalTickets"  :"1000",
    "bookingDeadline":"2024-7-20"
}
### Get all events
GET http://localhost:3000/events/allEvents
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YTE3OWZhNy05YTY2LTQyNmMtYjBmMi0zNTBiNjM2NjI4ZDIiLCJ1c2VyTmFtZSI6IktyaXN0ZW4iLCJwaG9uZU51bWJlciI6IjAxNDMyNzY1OTQiLCJlbWFpbCI6ImtyaXN0ZW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkaDd3V2U0azBSaWxQSVI2a1duUlp3dTNlV3lTWkp5akl1Y1kwcklqbmFoN3BsNHNFbzdweTIiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMzAzMzQ5LCJleHAiOjE3MjEzMTA1NDl9.ApIyMiqkSY9LpQLIikATGXCkTJeYa7yvPvFNVJ52mBo    

### update an event
POST http://localhost:3000/events/update/26a05f8d-6617-4e6d-bd18-95aa295b47e2
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YTE3OWZhNy05YTY2LTQyNmMtYjBmMi0zNTBiNjM2NjI4ZDIiLCJ1c2VyTmFtZSI6IktyaXN0ZW4iLCJwaG9uZU51bWJlciI6IjAxNDMyNzY1OTQiLCJlbWFpbCI6ImtyaXN0ZW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkaDd3V2U0azBSaWxQSVI2a1duUlp3dTNlV3lTWkp5akl1Y1kwcklqbmFoN3BsNHNFbzdweTIiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMjk1MDAxLCJleHAiOjE3MjEzMDIyMDF9.UX1hixizrKo30T1oG77dLralb_UkFctzLPNv5sBwfSA 

{
    "eventName" :"TaylorSwift concert",
    "startDate"  :"2024-7-22",
    "endDate" :"2024-7-26",
    "location" :"Tokyo",
    "description" :"Rocking with Zayn Malik",
    "longDescription"  :"6 days concert,day and night..Snacks are provided..Book now!!" ,
    "images"  :"https://th.bing.com/th/id/OIP.KUvp0P4OpY0dvpDA26DclwHaHi?rs=1&pid=ImgDetMain",
    "single"  :"2000",
    "couple"  :"3500",
    "groups"  :"8000",
    "totalTickets"  :"1000",
    "bookingDeadline":"2024-7-20"
}

### update event status
PUT http://localhost:3000/events/updateStatus/beff2247-cd05-414d-831a-14059ad186c6
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YTE3OWZhNy05YTY2LTQyNmMtYjBmMi0zNTBiNjM2NjI4ZDIiLCJ1c2VyTmFtZSI6IktyaXN0ZW4iLCJwaG9uZU51bWJlciI6IjAxNDMyNzY1OTQiLCJlbWFpbCI6ImtyaXN0ZW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkaDd3V2U0azBSaWxQSVI2a1duUlp3dTNlV3lTWkp5akl1Y1kwcklqbmFoN3BsNHNFbzdweTIiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMjk1MDAxLCJleHAiOjE3MjEzMDIyMDF9.UX1hixizrKo30T1oG77dLralb_UkFctzLPNv5sBwfSA 

### Approve all events
PUT http://localhost:3000/events/updateAllStatuses
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YTE3OWZhNy05YTY2LTQyNmMtYjBmMi0zNTBiNjM2NjI4ZDIiLCJ1c2VyTmFtZSI6IktyaXN0ZW4iLCJwaG9uZU51bWJlciI6IjAxNDMyNzY1OTQiLCJlbWFpbCI6ImtyaXN0ZW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkaDd3V2U0azBSaWxQSVI2a1duUlp3dTNlV3lTWkp5akl1Y1kwcklqbmFoN3BsNHNFbzdweTIiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMzExMTI1LCJleHAiOjE3MjEzMTgzMjV9.RAwlWIuAKWt886epcYZNGO7TqR7I4w6WNNIdN_NDXmQ

### Get one event
GET http://localhost:3000/events/oneEvent/26a05f8d-6617-4e6d-bd18-95aa295b47e2
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YTE3OWZhNy05YTY2LTQyNmMtYjBmMi0zNTBiNjM2NjI4ZDIiLCJ1c2VyTmFtZSI6IktyaXN0ZW4iLCJwaG9uZU51bWJlciI6IjAxNDMyNzY1OTQiLCJlbWFpbCI6ImtyaXN0ZW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkaDd3V2U0azBSaWxQSVI2a1duUlp3dTNlV3lTWkp5akl1Y1kwcklqbmFoN3BsNHNFbzdweTIiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMjk1MDAxLCJleHAiOjE3MjEzMDIyMDF9.UX1hixizrKo30T1oG77dLralb_UkFctzLPNv5sBwfSA 

### delete event
DELETE http://localhost:3000/events/delete/26a05f8d-6617-4e6d-bd18-95aa295b47e2
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YTE3OWZhNy05YTY2LTQyNmMtYjBmMi0zNTBiNjM2NjI4ZDIiLCJ1c2VyTmFtZSI6IktyaXN0ZW4iLCJwaG9uZU51bWJlciI6IjAxNDMyNzY1OTQiLCJlbWFpbCI6ImtyaXN0ZW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkaDd3V2U0azBSaWxQSVI2a1duUlp3dTNlV3lTWkp5akl1Y1kwcklqbmFoN3BsNHNFbzdweTIiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMjk1MDAxLCJleHAiOjE3MjEzMDIyMDF9.UX1hixizrKo30T1oG77dLralb_UkFctzLPNv5sBwfSA 

### Get all approved events
GET http://localhost:3000/events/approvedEvents
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YTE3OWZhNy05YTY2LTQyNmMtYjBmMi0zNTBiNjM2NjI4ZDIiLCJ1c2VyTmFtZSI6IktyaXN0ZW4iLCJwaG9uZU51bWJlciI6IjAxNDMyNzY1OTQiLCJlbWFpbCI6ImtyaXN0ZW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkaDd3V2U0azBSaWxQSVI2a1duUlp3dTNlV3lTWkp5akl1Y1kwcklqbmFoN3BsNHNFbzdweTIiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMjk1MDAxLCJleHAiOjE3MjEzMDIyMDF9.UX1hixizrKo30T1oG77dLralb_UkFctzLPNv5sBwfSA     

