### create an event
POST http://localhost:3000/events/create
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MzI2NTFmZS1mOTliLTRjYzMtOWYyZC00NjM5OTI1MDE1YzAiLCJ1c2VyTmFtZSI6Ik5hb21pMjUiLCJwaG9uZU51bWJlciI6IjAxNTQxNjY1ODMiLCJlbWFpbCI6Im5hb21pQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEzJHdQOEQ1eENjLkpqanNSbjFlTjF6WnVzTTBtRlVCSHNwWkVBZE9KZURJQ3VWWng3T283WmRxIiwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aC9pZC9SLjUwNjMxYzMxN2U2NmVlYmY0OTAwYzRmNDljNjMyY2Q3P3Jpaz1hQ3RiTEg4WVlEeVlqdyZwaWQ9SW1nUmF3JnI9MCIsImxvY2F0aW9uIjoic291dGhBZnJpY2EiLCJ1c2VyUm9sZSI6Im1hbmFnZXIiLCJpc01hbmFnZXIiOnRydWUsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZSI6ZmFsc2UsImlhdCI6MTcyMTY0MzI3OCwiZXhwIjoxNzIxNjUwNDc4fQ.h3iYq1PdOSX0FsrEAUpE7l6iGQ9tbhx5_Et3vBSLtVU

{
    "eventName" :"TaylorSwift concert",
    "startDate"  :"2024-7-22",
    "endDate" :"2024-7-26",
    "location" :"Instabul",
    "description" :"Rocking with Zayn Malik",
    "longDescription"  :"6 days concert,day and night..Snacks are provided..Book now!!" ,
    "images"  :"https://th.bing.com/th/id/OIP.KUvp0P4OpY0dvpDA26DclwHaHi?rs=1&pid=ImgDetMain",
    "single"  :"2000",
    "couple"  :"3500",
    "groups"  :"8000",
    "totalTickets"  :"6000",
    "bookingDeadline":"2024-7-20"
}
### Get all events
GET http://localhost:3000/events/allEvents
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYWRjOWQ4ZS02OTlkLTQxY2YtYmJiOC1mYjgxYTA3YmUyNjMiLCJ1c2VyTmFtZSI6Ik5hb21pQyIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU0MyIsImVtYWlsIjoibmFvbWljaGVnZTI1MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkZ1NCclprLmQyNExFTnN0UkFpQ05sdXVVUUx4MUNaUERFaVRiNVJMbE5pbmx1dC9qYlk3aW0iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJLaWVuaSIsInVzZXJSb2xlIjoiYWRtaW4iLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjE3MTk4NTksImV4cCI6MTcyMTcyNzA1OX0.Y2EhHFazVmLmuTxnqu3h2ZwVxIiV_EUAzAGcfCq1JQo


### update an event
POST http://localhost:3000/events/update/169c94d8-fbfc-440b-8b83-c00d1b0252de
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYWRjOWQ4ZS02OTlkLTQxY2YtYmJiOC1mYjgxYTA3YmUyNjMiLCJ1c2VyTmFtZSI6Ik5hb21pQyIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU0MyIsImVtYWlsIjoibmFvbWljaGVnZTI1MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkZ1NCclprLmQyNExFTnN0UkFpQ05sdXVVUUx4MUNaUERFaVRiNVJMbE5pbmx1dC9qYlk3aW0iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJLaWVuaSIsInVzZXJSb2xlIjoiYWRtaW4iLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjEzNzU0MTcsImV4cCI6MTcyMTM4MjYxN30.CGw2jr7NXomhGD9QDYd5x_f52X5726pM4AJSZkUOk6w

{
    "eventName" :"TaylorSwift concert",
    "startDate"  :"2024-7-22",
    "endDate" :"2024-7-26",
    "location" :"Instabul",
    "description" :"Rocking with Zayn Malik",
    "longDescription"  :"6 days concert,day and night..Snacks are provided..Book now!!" ,
    "images"  :"https://th.bing.com/th/id/OIP.KUvp0P4OpY0dvpDA26DclwHaHi?rs=1&pid=ImgDetMain",
    "single"  :"2000",
    "couple"  :"3500",
    "groups"  :"8000",
    "totalTickets"  :"8000",
    "bookingDeadline":"2024-7-20"
}

### Approve one event
PUT http://localhost:3000/events/updateStatus/169c94d8-fbfc-440b-8b83-c00d1b0252de
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYWRjOWQ4ZS02OTlkLTQxY2YtYmJiOC1mYjgxYTA3YmUyNjMiLCJ1c2VyTmFtZSI6Ik5hb21pQyIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU0MyIsImVtYWlsIjoibmFvbWljaGVnZTI1MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkZ1NCclprLmQyNExFTnN0UkFpQ05sdXVVUUx4MUNaUERFaVRiNVJMbE5pbmx1dC9qYlk3aW0iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJLaWVuaSIsInVzZXJSb2xlIjoiYWRtaW4iLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjE2NDM0OTQsImV4cCI6MTcyMTY1MDY5NH0.5x2blSD2DJC4QuuobuftDATisICbKVLzk18NRBBLSWM


### Approve all events
PUT http://localhost:3000/events/updateAllStatuses
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYWRjOWQ4ZS02OTlkLTQxY2YtYmJiOC1mYjgxYTA3YmUyNjMiLCJ1c2VyTmFtZSI6Ik5hb21pQyIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU0MyIsImVtYWlsIjoibmFvbWljaGVnZTI1MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkZ1NCclprLmQyNExFTnN0UkFpQ05sdXVVUUx4MUNaUERFaVRiNVJMbE5pbmx1dC9qYlk3aW0iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJLaWVuaSIsInVzZXJSb2xlIjoiYWRtaW4iLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjE3MTk4NTksImV4cCI6MTcyMTcyNzA1OX0.Y2EhHFazVmLmuTxnqu3h2ZwVxIiV_EUAzAGcfCq1JQo

### Get one event
GET http://localhost:3000/events/oneEvent/169c94d8-fbfc-440b-8b83-c00d1b0252de
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYWRjOWQ4ZS02OTlkLTQxY2YtYmJiOC1mYjgxYTA3YmUyNjMiLCJ1c2VyTmFtZSI6Ik5hb21pQyIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU0MyIsImVtYWlsIjoibmFvbWljaGVnZTI1MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkZ1NCclprLmQyNExFTnN0UkFpQ05sdXVVUUx4MUNaUERFaVRiNVJMbE5pbmx1dC9qYlk3aW0iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJLaWVuaSIsInVzZXJSb2xlIjoiYWRtaW4iLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjEzNzU0MTcsImV4cCI6MTcyMTM4MjYxN30.CGw2jr7NXomhGD9QDYd5x_f52X5726pM4AJSZkUOk6w

### Get an event
GET http://localhost:3000/events/anEvent
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MzI2NTFmZS1mOTliLTRjYzMtOWYyZC00NjM5OTI1MDE1YzAiLCJ1c2VyTmFtZSI6Ik5hb21pMjUiLCJwaG9uZU51bWJlciI6IjAxNTQxNjY1ODMiLCJlbWFpbCI6Im5hb21pQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEzJHdQOEQ1eENjLkpqanNSbjFlTjF6WnVzTTBtRlVCSHNwWkVBZE9KZURJQ3VWWng3T283WmRxIiwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aC9pZC9SLjUwNjMxYzMxN2U2NmVlYmY0OTAwYzRmNDljNjMyY2Q3P3Jpaz1hQ3RiTEg4WVlEeVlqdyZwaWQ9SW1nUmF3JnI9MCIsImxvY2F0aW9uIjoic291dGhBZnJpY2EiLCJ1c2VyUm9sZSI6Im1hbmFnZXIiLCJpc01hbmFnZXIiOnRydWUsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZSI6ZmFsc2UsImlhdCI6MTcyMTY0NDY1MiwiZXhwIjoxNzIxNjUxODUyfQ.v7uMfIFsrVcVvZyEzHeHV4_PIFV9cL2o2eDfUoVFbns

### delete event
DELETE http://localhost:3000/events/delete/169c94d8-fbfc-440b-8b83-c00d1b0252de
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYWRjOWQ4ZS02OTlkLTQxY2YtYmJiOC1mYjgxYTA3YmUyNjMiLCJ1c2VyTmFtZSI6Ik5hb21pQyIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU0MyIsImVtYWlsIjoibmFvbWljaGVnZTI1MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkZ1NCclprLmQyNExFTnN0UkFpQ05sdXVVUUx4MUNaUERFaVRiNVJMbE5pbmx1dC9qYlk3aW0iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJLaWVuaSIsInVzZXJSb2xlIjoiYWRtaW4iLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjEzODgyNTAsImV4cCI6MTcyMTM5NTQ1MH0.6B4UwSRSLyOya-cDtX5C7KnyeLUckqrwJ8iaxegHyHs


### Get all approved events
GET http://localhost:3000/events/approvedEvents
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYWRjOWQ4ZS02OTlkLTQxY2YtYmJiOC1mYjgxYTA3YmUyNjMiLCJ1c2VyTmFtZSI6Ik5hb21pQyIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU0MyIsImVtYWlsIjoibmFvbWljaGVnZTI1MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkZ1NCclprLmQyNExFTnN0UkFpQ05sdXVVUUx4MUNaUERFaVRiNVJMbE5pbmx1dC9qYlk3aW0iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJLaWVuaSIsInVzZXJSb2xlIjoiYWRtaW4iLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjE3MTk4NTksImV4cCI6MTcyMTcyNzA1OX0.Y2EhHFazVmLmuTxnqu3h2ZwVxIiV_EUAzAGcfCq1JQo


