### register user
POST http://localhost:3000/users/create
Content-type: application/json

{
    "userName" : "Ryankp",
    "phoneNumber" : "0143276584",
    "email" : "ryan@gmail.com",
    "password" : "@ryan25",
    "profileImage" : "https://th.bing.com/th/id/R.50631c317e66eebf4900c4f49c632cd7?rik=aCtbLH8YYDyYjw&pid=ImgRaw&r=0",
    "location" : "Thika",
    "userRole" : "attendee"
}

### Get all users
GET http://localhost:3000/users/allUsers
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YTE3OWZhNy05YTY2LTQyNmMtYjBmMi0zNTBiNjM2NjI4ZDIiLCJ1c2VyTmFtZSI6IktyaXN0ZW4iLCJwaG9uZU51bWJlciI6IjAxNDMyNzY1OTQiLCJlbWFpbCI6ImtyaXN0ZW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkaDd3V2U0azBSaWxQSVI2a1duUlp3dTNlV3lTWkp5akl1Y1kwcklqbmFoN3BsNHNFbzdweTIiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMzAzMzQ5LCJleHAiOjE3MjEzMTA1NDl9.ApIyMiqkSY9LpQLIikATGXCkTJeYa7yvPvFNVJ52mBo

### update User
PUT http://localhost:3000/users/update
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNTRkN2NkZi05YWVlLTRjNTAtOTEyZC01NjI0YjZjNjczMmUiLCJ1c2VyTmFtZSI6IlJ5YW5rcCIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU4NCIsImVtYWlsIjoicnlhbkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMyR2emJ0T2wvZWRmcW1adU92endqc0tPQThNSWhyLmoySkc5N29iNmJ1L2FJUDMwdHdOV1ZuaSIsInByb2ZpbGVJbWFnZSI6Imh0dHBzOi8vdGguYmluZy5jb20vdGgvaWQvUi41MDYzMWMzMTdlNjZlZWJmNDkwMGM0ZjQ5YzYzMmNkNz9yaWs9YUN0YkxIOFlZRHlZancmcGlkPUltZ1JhdyZyPTAiLCJsb2NhdGlvbiI6IlRoaWthIiwidXNlclJvbGUiOiJhdHRlbmRlZSIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZSI6ZmFsc2UsImlhdCI6MTcyMTIwNzI4NywiZXhwIjoxNzIxMjE0NDg3fQ.hcQ9H6Kki1aphCSmezLVMRdY5a9vINtWtjp6odkPk88


{
     "userName" : "Ryankpu",
    "phoneNumber" : "0143276584",
    "email" : "ryan@gmail.com",
    "password" : "@ryan25",
    "profileImage" : "https://th.bing.com/th/id/R.50631c317e66eebf4900c4f49c632cd7?rik=aCtbLH8YYDyYjw&pid=ImgRaw&r=0",
    "location" : "Thika",
    "userRole" : "manager"
}
### Get user by id
GET http://localhost:3000/users/user-id
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYWRjOWQ4ZS02OTlkLTQxY2YtYmJiOC1mYjgxYTA3YmUyNjMiLCJ1c2VyTmFtZSI6Ik5hb21pQyIsInBob25lTnVtYmVyIjoiMDE0MzI3NjU0MyIsImVtYWlsIjoibmFvbWljaGVnZTI1MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkZ1NCclprLmQyNExFTnN0UkFpQ05sdXVVUUx4MUNaUERFaVRiNVJMbE5pbmx1dC9qYlk3aW0iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJLaWVuaSIsInVzZXJSb2xlIjoiYWRtaW4iLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjEyMDM4MTUsImV4cCI6MTcyMTIxMTAxNX0.4v4VP0g5VKSLL2WYt4GGPpPIuogXYIJ9imCRMAxhAJU

### Get users by role
GET http://localhost:3000/users/user-role
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMTAzYzYyZi1iYzFkLTQzMjgtYTM4OS0yMWE4NGM2OGRjNTAiLCJ1c2VyTmFtZSI6IkxvdGhlIiwicGhvbmVOdW1iZXIiOiIwMTQzMjc2NTE0IiwiZW1haWwiOiJsb3RoZTEyQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEzJFBlNnc3OTBHcVhVT0FCdFdtRVl4V2VpYnphbzNlUnN4ZG5ad0VnOHlhQ3ZqSm05S2ppcGRHIiwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aC9pZC9SLjUwNjMxYzMxN2U2NmVlYmY0OTAwYzRmNDljNjMyY2Q3P3Jpaz1hQ3RiTEg4WVlEeVlqdyZwaWQ9SW1nUmF3JnI9MCIsImxvY2F0aW9uIjoiVGhpa2EiLCJ1c2VyUm9sZSI6ImF0dGVuZGVlIiwiaXNNYW5hZ2VyIjpmYWxzZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMjA0NDM5LCJleHAiOjE3MjEyMTE2Mzl9.vQGN8Sp3LwccxT7Dx5htk-9qRKAfGPoZb7JXQNvWicg

### Approving admins role
PUT http://localhost:3000/users/updateAll
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YTE3OWZhNy05YTY2LTQyNmMtYjBmMi0zNTBiNjM2NjI4ZDIiLCJ1c2VyTmFtZSI6IktyaXN0ZW4iLCJwaG9uZU51bWJlciI6IjAxNDMyNzY1OTQiLCJlbWFpbCI6ImtyaXN0ZW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkaDd3V2U0azBSaWxQSVI2a1duUlp3dTNlV3lTWkp5akl1Y1kwcklqbmFoN3BsNHNFbzdweTIiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoibWFuYWdlciIsImlzTWFuYWdlciI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMjg5NTcxLCJleHAiOjE3MjEyOTY3NzF9.8Be7Rv0zIqb9IdcDeyQWikbg_ipdXJSOFQQHwe9usaY
 

### soft delete a user
PUT http://localhost:3000/users/delete/a54d7cdf-9aee-4c50-912d-5624b6c6732e
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNWJkMmI4NS1kMWZkLTQ0MjUtYTE0NC0zZmEwYWFlNWJjOWEiLCJ1c2VyTmFtZSI6IkxvdGhlRiIsInBob25lTnVtYmVyIjoiMDE0MzI3NjUwNCIsImVtYWlsIjoibG90aGUxMUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMyRSclV4UWJqT1g4ZWVwUERrQzdPd1Bla3Y1cGlYdHBRems4dHVkWWNZc2ZSQVE1Ukp0YkRnVyIsInByb2ZpbGVJbWFnZSI6Imh0dHBzOi8vdGguYmluZy5jb20vdGgvaWQvUi41MDYzMWMzMTdlNjZlZWJmNDkwMGM0ZjQ5YzYzMmNkNz9yaWs9YUN0YkxIOFlZRHlZancmcGlkPUltZ1JhdyZyPTAiLCJsb2NhdGlvbiI6IlRoaWthIiwidXNlclJvbGUiOiJtYW5hZ2VyIiwiaXNNYW5hZ2VyIjpmYWxzZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMjA2NjA4LCJleHAiOjE3MjEyMTM4MDh9.sC-K0Vih29jqIV5JrEmZn1VkffnZtlQAtcz8PUDf7gQ

### retrieve deleted user
PUT http://localhost:3000/users/getUser/a54d7cdf-9aee-4c50-912d-5624b6c6732e
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNWJkMmI4NS1kMWZkLTQ0MjUtYTE0NC0zZmEwYWFlNWJjOWEiLCJ1c2VyTmFtZSI6IkxvdGhlRiIsInBob25lTnVtYmVyIjoiMDE0MzI3NjUwNCIsImVtYWlsIjoibG90aGUxMUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMyRSclV4UWJqT1g4ZWVwUERrQzdPd1Bla3Y1cGlYdHBRems4dHVkWWNZc2ZSQVE1Ukp0YkRnVyIsInByb2ZpbGVJbWFnZSI6Imh0dHBzOi8vdGguYmluZy5jb20vdGgvaWQvUi41MDYzMWMzMTdlNjZlZWJmNDkwMGM0ZjQ5YzYzMmNkNz9yaWs9YUN0YkxIOFlZRHlZancmcGlkPUltZ1JhdyZyPTAiLCJsb2NhdGlvbiI6IlRoaWthIiwidXNlclJvbGUiOiJtYW5hZ2VyIiwiaXNNYW5hZ2VyIjpmYWxzZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMjA2NjA4LCJleHAiOjE3MjEyMTM4MDh9.sC-K0Vih29jqIV5JrEmZn1VkffnZtlQAtcz8PUDf7gQ

###retrieve deleted users
PUT http://localhost:3000/users/getUsers
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNWJkMmI4NS1kMWZkLTQ0MjUtYTE0NC0zZmEwYWFlNWJjOWEiLCJ1c2VyTmFtZSI6IkxvdGhlRiIsInBob25lTnVtYmVyIjoiMDE0MzI3NjUwNCIsImVtYWlsIjoibG90aGUxMUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMyRSclV4UWJqT1g4ZWVwUERrQzdPd1Bla3Y1cGlYdHBRems4dHVkWWNZc2ZSQVE1Ukp0YkRnVyIsInByb2ZpbGVJbWFnZSI6Imh0dHBzOi8vdGguYmluZy5jb20vdGgvaWQvUi41MDYzMWMzMTdlNjZlZWJmNDkwMGM0ZjQ5YzYzMmNkNz9yaWs9YUN0YkxIOFlZRHlZancmcGlkPUltZ1JhdyZyPTAiLCJsb2NhdGlvbiI6IlRoaWthIiwidXNlclJvbGUiOiJtYW5hZ2VyIiwiaXNNYW5hZ2VyIjpmYWxzZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lIjpmYWxzZSwiaWF0IjoxNzIxMjA2NjA4LCJleHAiOjE3MjEyMTM4MDh9.sC-K0Vih29jqIV5JrEmZn1VkffnZtlQAtcz8PUDf7gQ