### register user
POST http://localhost:3000/users/create
Content-type: application/json

{
    "userName" : "Naomi25",
    "phoneNumber" : "0154166583",
    "email" : "naomi@gmail.com",
    "password" : "@Naomi2512",
    "profileImage" : "https://th.bing.com/th/id/R.50631c317e66eebf4900c4f49c632cd7?rik=aCtbLH8YYDyYjw&pid=ImgRaw&r=0",
    "location" : "southAfrica",
    "userRole" : "manager"
}

### Get all users
GET http://localhost:3000/users/allUsers
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MzI2NTFmZS1mOTliLTRjYzMtOWYyZC00NjM5OTI1MDE1YzAiLCJ1c2VyTmFtZSI6Ik5hb21pMjUiLCJwaG9uZU51bWJlciI6IjAxNTQxNjY1ODMiLCJlbWFpbCI6Im5hb21pQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEzJHdQOEQ1eENjLkpqanNSbjFlTjF6WnVzTTBtRlVCSHNwWkVBZE9KZURJQ3VWWng3T283WmRxIiwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aC9pZC9SLjUwNjMxYzMxN2U2NmVlYmY0OTAwYzRmNDljNjMyY2Q3P3Jpaz1hQ3RiTEg4WVlEeVlqdyZwaWQ9SW1nUmF3JnI9MCIsImxvY2F0aW9uIjoic291dGhBZnJpY2EiLCJ1c2VyUm9sZSI6Im1hbmFnZXIiLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjE1NzkxMTksImV4cCI6MTcyMTU4NjMxOX0.R5jHWqblBHiQjKXSaLVlBLXoOfGPXuJ7oG3X3kgSTxo

### update User
PUT http://localhost:3000/users/update
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NThhMjliOS1mMjMzLTQzY2UtODUzZS00NDU1M2U0MTdkZDciLCJ1c2VyTmFtZSI6IkFubjI1IiwicGhvbmVOdW1iZXIiOiIwMTQzMjY2NTQzIiwiZW1haWwiOiJhbm5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkMEYvY0VNa0ttd1cuU0VuYXFDajY3T25Xem1kRGhOUU5IRnVQTjI4eWFRQUlNWHlObURoVEsiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoiYXR0ZW5kZWUiLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjEzNzIxNjUsImV4cCI6MTcyMTM3OTM2NX0.4rcGURPesDKs96Igb7JSV_Y2FNOrMyLvM43E9ONeowU


{
     "userName" : "Ann25",
    "phoneNumber" : "0143266543",
    "email" : "ann@gmail.com",
    "password" : "@Ann2512",
    "profileImage" : "https://th.bing.com/th/id/R.50631c317e66eebf4900c4f49c632cd7?rik=aCtbLH8YYDyYjw&pid=ImgRaw&r=0",
    "location" : "Nyeri",
    "userRole" : "attendee"
}
### Get user by id
GET http://localhost:3000/users/user-id
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NThhMjliOS1mMjMzLTQzY2UtODUzZS00NDU1M2U0MTdkZDciLCJ1c2VyTmFtZSI6IkFubjI1IiwicGhvbmVOdW1iZXIiOiIwMTQzMjY2NTQzIiwiZW1haWwiOiJhbm5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkMEYvY0VNa0ttd1cuU0VuYXFDajY3T25Xem1kRGhOUU5IRnVQTjI4eWFRQUlNWHlObURoVEsiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoiYXR0ZW5kZWUiLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjEzNzIxNjUsImV4cCI6MTcyMTM3OTM2NX0.4rcGURPesDKs96Igb7JSV_Y2FNOrMyLvM43E9ONeowU

### Get managers
GET http://localhost:3000/users/user-role
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NThhMjliOS1mMjMzLTQzY2UtODUzZS00NDU1M2U0MTdkZDciLCJ1c2VyTmFtZSI6IkFubjI1IiwicGhvbmVOdW1iZXIiOiIwMTQzMjY2NTQzIiwiZW1haWwiOiJhbm5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkMEYvY0VNa0ttd1cuU0VuYXFDajY3T25Xem1kRGhOUU5IRnVQTjI4eWFRQUlNWHlObURoVEsiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoiYXR0ZW5kZWUiLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjEzNzIxNjUsImV4cCI6MTcyMTM3OTM2NX0.4rcGURPesDKs96Igb7JSV_Y2FNOrMyLvM43E9ONeowU

### Approving organizers role
PUT http://localhost:3000/users/updateAll
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MzI2NTFmZS1mOTliLTRjYzMtOWYyZC00NjM5OTI1MDE1YzAiLCJ1c2VyTmFtZSI6Ik5hb21pMjUiLCJwaG9uZU51bWJlciI6IjAxNTQxNjY1ODMiLCJlbWFpbCI6Im5hb21pQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEzJHdQOEQ1eENjLkpqanNSbjFlTjF6WnVzTTBtRlVCSHNwWkVBZE9KZURJQ3VWWng3T283WmRxIiwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aC9pZC9SLjUwNjMxYzMxN2U2NmVlYmY0OTAwYzRmNDljNjMyY2Q3P3Jpaz1hQ3RiTEg4WVlEeVlqdyZwaWQ9SW1nUmF3JnI9MCIsImxvY2F0aW9uIjoic291dGhBZnJpY2EiLCJ1c2VyUm9sZSI6Im1hbmFnZXIiLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjE1NzkyNTQsImV4cCI6MTcyMTU4NjQ1NH0.tUbGOKHz4UO7p3wQlKsKwPOr-tU_110IuTuehm97owE
 

### soft delete a user
PUT http://localhost:3000/users/delete/1adc9d8e-699d-41cf-bbb8-fb81a07be263
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NThhMjliOS1mMjMzLTQzY2UtODUzZS00NDU1M2U0MTdkZDciLCJ1c2VyTmFtZSI6IkFubjI1IiwicGhvbmVOdW1iZXIiOiIwMTQzMjY2NTQzIiwiZW1haWwiOiJhbm5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkMEYvY0VNa0ttd1cuU0VuYXFDajY3T25Xem1kRGhOUU5IRnVQTjI4eWFRQUlNWHlObURoVEsiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoiYXR0ZW5kZWUiLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjEzNzIxNjUsImV4cCI6MTcyMTM3OTM2NX0.4rcGURPesDKs96Igb7JSV_Y2FNOrMyLvM43E9ONeowU

### retrieve deleted user
PUT http://localhost:3000/users/getUser/05bd2b85-d1fd-4425-a144-3fa0aae5bc9a
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NThhMjliOS1mMjMzLTQzY2UtODUzZS00NDU1M2U0MTdkZDciLCJ1c2VyTmFtZSI6IkFubjI1IiwicGhvbmVOdW1iZXIiOiIwMTQzMjY2NTQzIiwiZW1haWwiOiJhbm5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkMEYvY0VNa0ttd1cuU0VuYXFDajY3T25Xem1kRGhOUU5IRnVQTjI4eWFRQUlNWHlObURoVEsiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoiYXR0ZW5kZWUiLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjEzNzIxNjUsImV4cCI6MTcyMTM3OTM2NX0.4rcGURPesDKs96Igb7JSV_Y2FNOrMyLvM43E9ONeowU

###retrieve deleted users
PUT http://localhost:3000/users/getUsers
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NThhMjliOS1mMjMzLTQzY2UtODUzZS00NDU1M2U0MTdkZDciLCJ1c2VyTmFtZSI6IkFubjI1IiwicGhvbmVOdW1iZXIiOiIwMTQzMjY2NTQzIiwiZW1haWwiOiJhbm5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTMkMEYvY0VNa0ttd1cuU0VuYXFDajY3T25Xem1kRGhOUU5IRnVQTjI4eWFRQUlNWHlObURoVEsiLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL1IuNTA2MzFjMzE3ZTY2ZWViZjQ5MDBjNGY0OWM2MzJjZDc_cmlrPWFDdGJMSDhZWUR5WWp3JnBpZD1JbWdSYXcmcj0wIiwibG9jYXRpb24iOiJUaGlrYSIsInVzZXJSb2xlIjoiYXR0ZW5kZWUiLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWUiOmZhbHNlLCJpYXQiOjE3MjEzNzIxNjUsImV4cCI6MTcyMTM3OTM2NX0.4rcGURPesDKs96Igb7JSV_Y2FNOrMyLvM43E9ONeowU